offer_table:
    path:     /admin/offer/table
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::tableAction }

offer_add:
    path:     /admin/offer/add
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::addAction }

offer_view:
    path:     /admin/offer/view/{id}
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::viewAction }
    requirements:
        id: \d+

offer_update:
    path:     /admin/offer/update/{id}
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::updateAction }
    requirements:
        id: \d+

offer_delete:
    path:     /admin/offer/delete/{id}
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::deleteAction }
    requirements:
            id: \d+

offer_send:
    path:     /admin/offer/{id}/send
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::sendEmailAction }
    requirements:
        id: \d+

offer_print:
    path:   /admin/offer/{id}/print
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::printAction }
    requirements:
        id: \d+

offer_rough:
    path:   /admin6834/offer/{id}/rough
    defaults: { _controller: Dywee\OrderBundle\Controller\OfferController::roughAction }
    requirements:
        id: \d+

order_list:
    path:     /admin/order/list
    defaults: { _controller: Dywee\OrderBundle\Controller\OrderAdminController::listAction }