services:
    dywee_order.doctrine.invoice_reference:
        class: Dywee\OrderBundle\Service\InvoiceReferenceManager
        arguments: [ ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    #dywee_order.doctrine.stockmanager:
    #        class: Dywee\OrderBundle\DoctrineListener\StockManager
    #        arguments: [ ]
    #        tags:
    #            - { name: doctrine.event_listener, event: prePersist }
    #            - { name: doctrine.event_listener, event: preUpdate }

    dywee_order.admin_sidebar_listener:
        class: Dywee\OrderBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_order.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_order.sidebar_handler:
        class: Dywee\OrderBundle\Service\OrderAdminSidebarHandler
        arguments: [ '@router' ]

    ####### SHIPMENT ######
    dywee_order.shipment_calculator:
        class: Dywee\OrderBundle\Service\ShipmentCalculator
        arguments: [  ]

    dywee_order.shipment_method:
        class: Dywee\OrderBundle\Service\ShipmentMethod
        arguments: [ '@doctrine.orm.entity_manager' ]