services:
    dywee_order.invoice_reference:
        class: Dywee\OrderBundle\Service\InvoiceReferenceManager
        arguments: [ ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    #dywee_order.doctrine.stockmanager:
    #        class: Dywee\OrderBundle\DoctrineListener\StockManager
    #        arguments: [ ]
    #        tags:
    #            - { name: doctrine.event_listener, event: prePersist }
    #            - { name: doctrine.event_listener, event: preUpdate }




    ###########################
    #                         #
    #         SIDEBAR         #
    #                         #
    ###########################

    dywee_order.admin_sidebar_listener:
        class: Dywee\OrderBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_order.sidebar_handler', true ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_order.sidebar_handler:
        class: Dywee\OrderBundle\Service\AdminSidebarHandler
        arguments: [ '@router' ]

    ###########################
    #                         #
    #        DASHBOARD        #
    #                         #
    ###########################

    dywee_order_cms.admin_dashboard_listener:
        class: Dywee\OrderCMSBundle\Listener\AdminDashboardBuilderListener
        arguments: [ '@dywee_order_cms.dashboard_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_order_cms.dashboard_handler:
        class: Dywee\OrderCMSBundle\Service\OrderCMSAdminDashboardHandler
        arguments: [ '@router' ]



    ###########################
    #                         #
    #         SHIPMENT        #
    #                         #
    ###########################

    dywee_order.shipment_calculator:
        class: Dywee\OrderBundle\Service\ShipmentCalculator
        #arguments: [ '@dywee_order.shipment_rule_manager' ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    dywee_order.shipment_method:
        class: Dywee\OrderBundle\Service\ShippingMethod
        arguments: [ '@doctrine.orm.entity_manager' ]

    dywee_order.shipment_rule_manager:
        class: Dywee\OrderBundle\Service\ShipmentRuleManager
        arguments: ['@doctrine.orm.entity_manager']

    ###########################
    #                         #
    #         MANAGER         #
    #                         #
    ###########################

    dywee_order.status_manager:
        class: Dywee\OrderBundle\Service\OrderStatusManager