services:

    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true

    Dywee\OrderBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{DependencyInjection,Entity,Event,Listener,Repository,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Dywee\OrderBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    dywee_order.invoice_reference:
        class: Dywee\OrderBundle\Service\InvoiceReferenceManager
        arguments: [ ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    #dywee_order.doctrine.stockmanager:
    #        class: Dywee\OrderBundle\DoctrineListener\StockManager
    #        arguments: [ ]
    #        tags:
    #            - { name: doctrine.event_listener, event: prePersist }
    #            - { name: doctrine.event_listener, event: preUpdate }




    ###########################
    #                         #
    #         SIDEBAR         #
    #                         #
    ###########################

    dywee_order.admin_sidebar_listener:
        class: Dywee\OrderBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_order.sidebar_handler', true ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_order.sidebar_handler:
        class: Dywee\OrderBundle\Service\AdminSidebarHandler
        arguments: [ '@router' ]


    ###########################
    #                         #
    #        DASHBOARD        #
    #                         #
    ###########################

    dywee_order_cms.admin_dashboard_listener:
        class: Dywee\OrderCMSBundle\Listener\AdminDashboardBuilderListener
        arguments: [ '@dywee_order_cms.dashboard_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_order_cms.dashboard_handler:
        class: Dywee\OrderCMSBundle\Service\OrderCMSAdminDashboardHandler
        arguments: [ '@router' ]


    ###########################
    #                         #
    #        SHIPMENTS        #
    #                         #
    ###########################

    dywee_order.shipment_calculator:
        class: Dywee\OrderBundle\Service\ShipmentCalculator
        #arguments: [ '@dywee_order.shipment_rule_manager' ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    dywee_order.shipment_method:
        class: Dywee\OrderBundle\Service\ShippingMethodHandler
        arguments: [ '@doctrine.orm.entity_manager' ]

    dywee_order.shipment_rule_manager:
        class: Dywee\OrderBundle\Service\ShipmentRuleManager
        arguments: ['@doctrine.orm.entity_manager']


    ###########################
    #                         #
    #         MANAGERS        #
    #                         #
    ###########################

    dywee_order.order_element_manager:
        class: Dywee\OrderBundle\Service\OrderElementManager

    dywee_order.status_manager:
        class: Dywee\OrderBundle\Service\OrderStatusManager

    Dywee\OrderBundle\Service\OrderVirtualizationManager:
        class: Dywee\OrderBundle\Service\OrderVirtualizationManager

    dywee_order.payment_validated_listener:
        class: Dywee\OrderBundle\Listener\PaymentValidatedListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: order.payment_validated, method: onPaymentValidated }


    ###########################
    #                         #
    #          FORMS          #
    #                         #
    ###########################

    dywee_order.shipping_options_type:
        class: Dywee\OrderBundle\Form\ShippingOptionsType
        arguments: ['@dywee_order.shipment_method']
        tags:
        - { name: form.type }