dywee_order_admin_table:
    path:     /admin6833/order/table/{state}/{page}
    defaults: { _controller: DyweeOrderBundle:Order:table, state: 2, page: 1 }

dywee_order_add:
    path:     /admin6833/order/add
    defaults: { _controller: DyweeOrderBundle:Order:add }

dywee_order_view:
    path:     /admin6833/order/view/{id}
    defaults: { _controller: DyweeOrderBundle:Order:view }
    requirements:
        id: \d+

dywee_order_update:
    path:     /admin6833/order/update/{id}
    defaults: { _controller: DyweeOrderBundle:Order:update }
    requirements:
            id: \d+

dywee_order_delete:
    path:     /admin6833/order/delete/{id}
    defaults: { _controller: DyweeOrderBundle:Order:delete }
    requirements:
            id: \d+

dywee_invoice_view:
    path:     /invoice/{id}/view
    defaults: { _controller: DyweeOrderBundle:Order:invoiceView }
    requirements:
        id: \d+

dywee_invoice_user_view:
    path:     /invoice/view/{invoiceReference}
    defaults: { _controller: DyweeOrderBundle:Order:invoiceUserView }

dywee_order_invoice_download:
    path:     /admin6833/order/invoice/{idOrder}/download
    defaults: { _controller: DyweeOrderBundle:Order:invoiceDownload }
    requirements:
            id: \d+

dywee_order_confirmation_succeed:
    path:    /order/{reference}/confirmation/success
    defaults: { _controller: DyweeOrderBundle:Basket:confirmationSuccess }

dywee_order_confirmation_cancel:
    path:    /order/{reference}/confirmation/cancel
    defaults: { _controller: DyweeOrderBundle:Basket:confirmationCancel }

dywee_view_email:
    path:    /view/email/{idOrder}/{number}
    defaults: { _controller: DyweeOrderBundle:Order:viewEmail}
    requirements:
        number: \d+

dywee_offer_table:
    path:     /admin6833/offer/table
    defaults: { _controller: DyweeOrderBundle:Offer:table }

dywee_offer_add:
    path:     /admin6833/offer/add
    defaults: { _controller: DyweeOrderBundle:Offer:add }

dywee_offer_view:
    path:     /admin6833/offer/view/{id}
    defaults: { _controller: DyweeOrderBundle:Offer:view }
    requirements:
        id: \d+

dywee_offer_update:
    path:     /admin6833/offer/update/{id}
    defaults: { _controller: DyweeOrderBundle:Offer:update }
    requirements:
        id: \d+

dywee_offer_delete:
    path:     /admin6833/offer/delete/{id}
    defaults: { _controller: DyweeOrderBundle:Offer:delete }
    requirements:
            id: \d+

dywee_order_export_csv:
    path:   /admin6833/order/export/{type}
    defaults: { _controller: DyweeOrderBundle:Order:exportToCSV, type: all }

dywee_offer_send:
    path:     /admin6833/offer/{id}/send
    defaults: { _controller: DyweeOrderBundle:Offer:sendEmail }
    requirements:
        id: \d+

dywee_offer_print:
    path:   /admin6833/offer/{id}/print
    defaults: { _controller: DyweeOrderBundle:Offer:print }
    requirements:
        id: \d+

dywee_offer_rough:
    path:   /admin6834/offer/{id}/rough
    defaults: { _controller: DyweeOrderBundle:Offer:rough }
    requirements:
        id: \d+

dywee_order_table_current_month:
    path:     /admin6833/order/table/current_month/{state}
    defaults: { _controller: DyweeOrderBundle:Order:currentTable, state: 2 }
    requirements:
        state: \d*

dywee_order_paypal_checkout:
    path:     /basket/paypal-checkout
    defaults: { _controller: DyweeCartBundle:Basket:paypalCheckout }

dywee_order_paypal_validation:
    path:     /paypal-confirmation/{type}/{reference}
    defaults: { _controller: DyweeOrderBundle:Order:paypalConfirmation }
    requirements:
        type: success|cancelled

dywee_order_validated:
    path:     /order/validated
    defaults: { _controller: DyweeOrderBundle:Order:validated }

dywee_paypal_ajax:
    path: /order/paypalSetup
    defaults: { _controller: DyweeCartBundle:Basket:paypalCheckoutAjax }
    requirements:
        _methods: POST

dywee_order_list:
    path:     /admin6833/order/list
    defaults: { _controller: DyweeOrderBundle:OrderAdmin:list }

dywee_order_payment_overview:
    path:     /admin6833/order/{id}/payment
    defaults: { _controller: DyweeOrderBundle:OrderAdmin:paymentOverview }