<?php

namespace Dywee\OrderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderElementRepository extends EntityRepository
{

}
