<?php

namespace Dywee\OrderBundle\Repository;

/**
 * OrderReferenceBuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderReferenceBuilderRepository extends \Doctrine\ORM\EntityRepository
{

}
