<?php

namespace Dywee\OrderBundle\Repository;

/**
 * OrderStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatRepository extends \Doctrine\ORM\EntityRepository
{
}
