<?php

namespace Dywee\OrderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderElementRepository extends EntityRepository
{

}
