<?php

namespace Dywee\OrderBundle\Repository;

/**
 * OrderStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStateRepository extends \Doctrine\ORM\EntityRepository
{
}
