<?php

namespace Dywee\OrderBundle\Repository;

/**
 * ReferenceIteratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceIteratorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findItertor($builder, $country)
    {
        $qb = $this->createQueryBuilder('ri')
            ->select('ri');

        if ($builder->getByCountry()) {
            $qb->where('ri.country = :country')
                ->setParameter('country', $country);
        }

        return $qb->getQuery()->getResult();
    }
}
