<?php

namespace Dywee\OrderBundle\Controller;

use CoreBundle\Controller\ParentController;
use Dywee\OrderBundle\Entity\OrderReferenceBuilder;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class OrderReferenceBuilderController extends ParentController
{

    /**
     * @param $id
     * @param Request $request
     * @param null $parameters
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @Route(name="order_reference_update", path="admin/order/reference/update")
     */
    public function myUpdateAction(Request $request, $parameters = null)
    {
        $em = $this->getDoctrine()->getManager();
        $orderReferenceBuilderRepository = $em->getRepository('DyweeOrderBundle:OrderReferenceBuilder');
        $orderReferenceBuilder = $orderReferenceBuilderRepository->findById(1);

        // Create default builder if not existing
        if(!$orderReferenceBuilder)
        {
            $orderReferenceBuilder = new OrderReferenceBuilder();
            $em->persist($orderReferenceBuilder);
            $em->flush();
        }

        return parent::updateAction(1, $request, $parameters); // TODO: Change the autogenerated stub
    }
}